name: cooljeanius/ClipboardViewer
on:
  push:
    branches:
    - "**/*"
  pull_request:
jobs:
  test:
    runs-on: macos-11.0
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.2
#     # 'Transformers::TravisCI::Scripts::Dependencies' dependencies are currently unsupported
#     # 'compiler' was not transformed because there is no suitable equivalent in GitHub Actions
    - run: echo "Not everyone uses CocoaPods"
    - run: xcodebuild
    strategy:
      matrix:
        compiler:
        - clang
        - gcc
